== Compressed Instructions

.Compressed 16-bit RVC Instruction Formats
[float="center",align="center",cols="1a, 2a",frame="none",grid="none"]
|===
|
[%autowidth,float="right",align="right",cols="^,^",frame="none",grid="none",options="noheader"]
!===
!Format ! Meaning
!CR ! Register
!CI ! Immediate
!CSS ! Stack-relative Store
!CIW ! Wide Immediate
!CL ! Load
!CS ! Store
!CA ! Arithmetic
!CB ! Branch/Arithmetic
!CJ ! Jump
!===
|
[float="left",align="left",cols="1,1,1,1,1,1,1",options="noheader"]
!===
^!15 14 13 ^!12 ^!11 10 ^!9 8 7 ^!6 5 ^!4 3 2 ^!1 0
2+^!funct4 2+^!rd/rs1 2+^!rs2 ^!  op
^!funct3 ^!imm 2+^!rd/rs1  2+^!imm ^!  op
^!funct3 3+^!imm  2+^!rs2 ^!  op
^!funct3 4+^!imm ^!rd{prime} ^! op
^!funct3 2+^!imm ^!rs1{prime} ^!imm ^!rd{prime} ^! op
^!funct3 2+^!imm ^!rs1{prime} ^! imm ^!rs2{prime} ^! op
3+^!funct6 ^!rd{prime}/rs1{prime} ^!funct2 ^!rs2{prime} ^! op
^!funct3 2+^!offset ^!rd{prime}/rs1{prime} 2+^!offset ^! op
^!funct3 5+^!jump target ^! op
!===
|===

.Registers Specified by the Three-Bit _rs1_{prime}, _rs2_{prime}, and _rd_{prime} fields of the CIW, CL, CS, CA, and CB Formats
[float="center",align="center",cols="1a, 1a",frame="none",grid="none"]
|===
|
[%autowidth,cols="<",frame="none",grid="none",options="noheader"]
!===
!RVC Register Number
!Integer Register Number
!Integer Register ABI Name
!Floating-Point Register Number
!Floating-Point Register ABI Name
!===
|

[%autowidth,cols="^,^,^,^,^,^,^,^",options="noheader"]
!===
!`000` !`001` !`010` !`011` !`100` !`101` !`110` !`111`
!`x8` !`x9` !`x10` !`x11` !`x12` !`x13` !`x14`!`x15`
!`s0` !`s1` !`a0` !`a1` !`a2` !`a3` !`a4`!`a5`
!`f8` !`f9` !`f10` !`f11` !`f12` !`f13`!`f14` !`f15`
!`fs0` !`fs1` !`fa0` !`fa1` !`fa2`!`fa3` !`fa4` !`fa5`
!===
|===

.RVC HINT Instructions
[cols="<,<,>,<",options="header",]
|===
|Instruction |Constraints |Code Points |Purpose

|C.NOP |_imm_≠0 |63 .6+.^|_Designated for future standard use_

|C.ADDI | _rd_≠`x0`, _imm_=0 |31

|C.LI | _rd_=`x0` |64

|C.LUI | _rd_=`x0`, _imm_≠0 |63

|C.MV | _rd_=`x0`, _rs2_≠`x0` |31

|C.ADD | _rd_=`x0`, _rs2_≠`x0`, _rs2_≠`x2-x5` | 27

|C.ADD | _rd_=`x0`, _rs2_=`x2-x5` |4|(rs2=x2) C.NTL.P1 (rs2=x3) C.NTL.PALL (rs2=x4) C.NTL.S1 (rs2=x5) C.NTL.ALL

|C.SLLI |_rd_=`x0` or _imm_=0 |63 (RV32), 95 (RV64)  .3+.^|_Designated for custom use_

|C.SRLI | _imm_=0 |8

|C.SRAI | _imm_=0 |8
|===

<<<

.RVC Opcode Map Instructions
[%autowidth,float="center",align="center",cols=">,^,^,^,^,^,^,^,^,^,<]
|===
2+>|inst[15:13] +
inst[1:0] ^.^s|000 ^.^s|001 ^.^s|010 ^.^s|011 ^.^s|100 ^.^s|101 ^.^s|110 ^.^s|111 |

2+>.^|00 .^|ADDI4SPN ^.^|FLD +
FLD ^.^| LW ^.^| FLW +
LD ^.^| _Reserved_ ^.^| FSD +
FSD ^.^| SW ^.^| FSW +
SD
^.^| RV32 +
RV64

2+>.^|01 ^.^|ADDI ^.^|JAL +
ADDIW ^.^|LI ^.^|LUI/ADDI16SP ^.^|MISC-ALU ^.^|J ^.^|BEQZ ^.^|BNEZ ^.^|RV32 +
RV64

2+>.^|10 ^.^|SLLI ^.^|FLDSP +
FLDSP ^.^|LWSP ^.^|FLWSP +
LDSP ^.^|J[AL]R/MV/ADD ^.^|FSDSP +
FSDSP ^.^|SWSP ^.^|FSWSP +
SDSP ^.^|RV32 +
RV64

2+>.^|11 9+^|>16b
|===
